services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: parcial
      POSTGRES_USER: parcial
      POSTGRES_PASSWORD: parcial
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parcial -d parcial"]
      interval: 5s
      timeout: 5s
      retries: 20

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: parcial
      MYSQL_USER: parcial
      MYSQL_PASSWORD: parcial
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -proot"]
      interval: 5s
      timeout: 5s
      retries: 30

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      APP_SECURITY_JWT_SECRET: "CHANGE_ME_TO_A_32+_BYTE_SECRET_FOR_HS256_2026"
    ports:
      - "8080:8080"

