spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres:5432/parcial}
    username: ${SPRING_R2DBC_USERNAME:parcial}
    password: ${SPRING_R2DBC_PASSWORD:parcial}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

app:
  db:
    schema: classpath:db/schema-postgres.sql
